services:
  - type: web
    name: outdoor-digital
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
    healthCheckPath: /
    instanceCount: 1
    instanceSize: free
    autoDeploy: true
    env:
      - key: PYTHONPATH
        value: .
    plan: free
